In [1]:
import torch
import numpy as np
import pandas as pd

In [2]:
data=pd.read_excel(r'C:\Users\Julaysa\Машинное обучение\Задачи регрессии\Fakticheskie_dannye.xlsx')
#Нормализация данных
from sklearn import preprocessing
data_x=data.iloc[:,:14] #Нормализуем x
data_x = preprocessing.normalize(data_x)
data_x = pd.DataFrame(data_x)

In [3]:
# Данные
x=data_x.iloc[:,:14]
y=data.iloc[:,-1]



from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20)



# конвертируем данные
x_train=torch.tensor(x_train.values).type(torch.FloatTensor)
y_train=torch.tensor(y_train.values).type(torch.FloatTensor)
x_test=torch.tensor(x_test.values).type(torch.FloatTensor)
y_test=torch.tensor(y_test.values).type(torch.FloatTensor)


#Транспонируем векторы-строки в векторы-столбцы
x_train.unsqueeze_(1)
y_train.unsqueeze_(1);

In [4]:
class SineNet(torch.nn.Module):
    def __init__(self, n_hidden_neurons):
        super(SineNet, self).__init__()
        self.fc1 = torch.nn.Linear(14, n_hidden_neurons) #первый слой 
        self.act1 = torch.nn.Sigmoid() # функция активации 
        self.fc2 = torch.nn.Linear(n_hidden_neurons, 1) #второй слой 

    def forward(self, x):
        x = self.fc1(x)
        x = self.act1(x)
        x = self.fc2(x)
        return x

sine_net = SineNet(1500) # Колличество нейронов 

In [5]:
def predict(net, x, y):
    y_pred = net.forward(x)

In [6]:
# Оптимизатор градиентного спуска  
optimizer = torch.optim.Adam(sine_net.parameters(), lr=0.001)

In [7]:
# Функция потерь
loss=torch.nn.MSELoss()

In [14]:
for epoch_index in range(1000):
    optimizer.zero_grad() # Обнуляем градиенты
    y_pred = sine_net.forward(x_train)
    loss_val = loss(y_pred, y_train) # Функция потерь
    loss_val.backward() # Производная
    optimizer.step()
    print("Эпоха",epoch_index,"Функция потерь",loss_val)

C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\loss.py:446: UserWarning: Using a target size (torch.Size([144, 1])) that is different to the input size (torch.Size([144, 1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


Эпоха 0 Функция потерь tensor(15.7291, grad_fn=<MseLossBackward>)
Эпоха 1 Функция потерь tensor(15.7282, grad_fn=<MseLossBackward>)
Эпоха 2 Функция потерь tensor(15.7278, grad_fn=<MseLossBackward>)
Эпоха 3 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 4 Функция потерь tensor(15.7279, grad_fn=<MseLossBackward>)
Эпоха 5 Функция потерь tensor(15.7283, grad_fn=<MseLossBackward>)
Эпоха 6 Функция потерь tensor(15.7288, grad_fn=<MseLossBackward>)
Эпоха 7 Функция потерь tensor(15.7293, grad_fn=<MseLossBackward>)
Эпоха 8 Функция потерь tensor(15.7298, grad_fn=<MseLossBackward>)
Эпоха 9 Функция потерь tensor(15.7303, grad_fn=<MseLossBackward>)
Эпоха 10 Функция потерь tensor(15.7307, grad_fn=<MseLossBackward>)
Эпоха 11 Функция потерь tensor(15.7310, grad_fn=<MseLossBackward>)
Эпоха 12 Функция потерь tensor(15.7312, grad_fn=<MseLossBackward>)
Эпоха 13 Функция потерь tensor(15.7312, grad_fn=<MseLossBackward>)
Эпоха 14 Функция потерь tensor(15.7312, grad_fn=<MseLossBackward>)
Эпоха

Эпоха 140 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 141 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 142 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 143 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 144 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 145 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 146 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 147 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 148 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 149 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 150 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 151 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 152 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 153 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 154 Функция потерь tensor(15.7277, grad_fn

Эпоха 278 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 279 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 280 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 281 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 282 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 283 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 284 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 285 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 286 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 287 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 288 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 289 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 290 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 291 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 292 Функция потерь tensor(15.7277, grad_fn

Эпоха 415 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 416 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 417 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 418 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 419 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 420 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 421 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 422 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 423 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 424 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 425 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 426 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 427 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 428 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 429 Функция потерь tensor(15.7277, grad_fn

Эпоха 555 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 556 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 557 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 558 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 559 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 560 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 561 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 562 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 563 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 564 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 565 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 566 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 567 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 568 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 569 Функция потерь tensor(15.7277, grad_fn

Эпоха 691 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 692 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 693 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 694 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 695 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 696 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 697 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 698 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 699 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 700 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 701 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 702 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 703 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 704 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 705 Функция потерь tensor(15.7277, grad_fn

Эпоха 828 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 829 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 830 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 831 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 832 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 833 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 834 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 835 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 836 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 837 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 838 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 839 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 840 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 841 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 842 Функция потерь tensor(15.7277, grad_fn

Эпоха 964 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 965 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 966 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 967 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 968 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 969 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 970 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 971 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 972 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 973 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 974 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 975 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 976 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 977 Функция потерь tensor(15.7277, grad_fn=<MseLossBackward>)
Эпоха 978 Функция потерь tensor(15.7277, grad_fn

In [15]:
# Открываем файл
data_new = pd.read_excel(r'C:\Users\Julaysa\Машинное обучение\Задачи регрессии\Zadanie.xlsx')
x_new=data_new.iloc[:,:14]

#Нормализация данных
x_new = preprocessing.normalize(x_new)
x_new = pd.DataFrame(x_new)
# конвертируем данные
x_new=torch.tensor(x_new.values).type(torch.FloatTensor)
x_new.unsqueeze_(1)

# Прогноз
y_pred = sine_net.forward(x_new)
for i in y_pred:
    print(i)

tensor([[20.8706]], grad_fn=<UnbindBackward>)
tensor([[20.8800]], grad_fn=<UnbindBackward>)
tensor([[20.8769]], grad_fn=<UnbindBackward>)
tensor([[20.8711]], grad_fn=<UnbindBackward>)
tensor([[20.8720]], grad_fn=<UnbindBackward>)
tensor([[20.8718]], grad_fn=<UnbindBackward>)
tensor([[20.8716]], grad_fn=<UnbindBackward>)
tensor([[20.8716]], grad_fn=<UnbindBackward>)
tensor([[20.8714]], grad_fn=<UnbindBackward>)
tensor([[20.8716]], grad_fn=<UnbindBackward>)
tensor([[20.8714]], grad_fn=<UnbindBackward>)
tensor([[20.8715]], grad_fn=<UnbindBackward>)
tensor([[20.8714]], grad_fn=<UnbindBackward>)
tensor([[20.8713]], grad_fn=<UnbindBackward>)
tensor([[20.8718]], grad_fn=<UnbindBackward>)
tensor([[20.8717]], grad_fn=<UnbindBackward>)
tensor([[20.8718]], grad_fn=<UnbindBackward>)
tensor([[20.8720]], grad_fn=<UnbindBackward>)
tensor([[20.8723]], grad_fn=<UnbindBackward>)
tensor([[20.8725]], grad_fn=<UnbindBackward>)
tensor([[20.8720]], grad_fn=<UnbindBackward>)
tensor([[20.8713]], grad_fn=<Unbin

tensor([[20.8740]], grad_fn=<UnbindBackward>)
tensor([[20.8736]], grad_fn=<UnbindBackward>)
tensor([[20.8700]], grad_fn=<UnbindBackward>)
tensor([[20.8710]], grad_fn=<UnbindBackward>)
tensor([[20.8733]], grad_fn=<UnbindBackward>)
tensor([[20.8733]], grad_fn=<UnbindBackward>)
tensor([[20.8733]], grad_fn=<UnbindBackward>)
tensor([[20.8733]], grad_fn=<UnbindBackward>)
tensor([[20.8731]], grad_fn=<UnbindBackward>)
tensor([[20.8733]], grad_fn=<UnbindBackward>)
tensor([[20.8733]], grad_fn=<UnbindBackward>)
tensor([[20.8739]], grad_fn=<UnbindBackward>)
tensor([[20.8738]], grad_fn=<UnbindBackward>)
tensor([[20.8737]], grad_fn=<UnbindBackward>)
tensor([[20.8739]], grad_fn=<UnbindBackward>)
tensor([[20.8743]], grad_fn=<UnbindBackward>)
tensor([[20.8744]], grad_fn=<UnbindBackward>)
tensor([[20.8734]], grad_fn=<UnbindBackward>)
tensor([[20.8726]], grad_fn=<UnbindBackward>)
tensor([[20.8723]], grad_fn=<UnbindBackward>)


IndexError: too many indices for tensor of dimension 3